// Helper function to convert country code to flag emoji
const getFlagEmoji = (countryCode: string) => {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
};

export const countries = [
  { code: "AF", name: "Afghanistan", flag: getFlagEmoji("AF") },
  { code: "AL", name: "Albania", flag: getFlagEmoji("AL") },
  { code: "DZ", name: "Algeria", flag: getFlagEmoji("DZ") },
  { code: "AR", name: "Argentina", flag: getFlagEmoji("AR") },
  { code: "AM", name: "Armenia", flag: getFlagEmoji("AM") },
  { code: "AU", name: "Australia", flag: getFlagEmoji("AU") },
  { code: "AT", name: "Austria", flag: getFlagEmoji("AT") },
  { code: "AZ", name: "Azerbaijan", flag: getFlagEmoji("AZ") },
  { code: "BD", name: "Bangladesh", flag: getFlagEmoji("BD") },
  { code: "BY", name: "Belarus", flag: getFlagEmoji("BY") },
  { code: "BE", name: "Belgium", flag: getFlagEmoji("BE") },
  { code: "BR", name: "Brazil", flag: getFlagEmoji("BR") },
  { code: "BG", name: "Bulgaria", flag: getFlagEmoji("BG") },
  { code: "CA", name: "Canada", flag: getFlagEmoji("CA") },
  { code: "CL", name: "Chile", flag: getFlagEmoji("CL") },
  { code: "CN", name: "China", flag: getFlagEmoji("CN") },
  { code: "CO", name: "Colombia", flag: getFlagEmoji("CO") },
  { code: "HR", name: "Croatia", flag: getFlagEmoji("HR") },
  { code: "CZ", name: "Czech Republic", flag: getFlagEmoji("CZ") },
  { code: "DK", name: "Denmark", flag: getFlagEmoji("DK") },
  { code: "EG", name: "Egypt", flag: getFlagEmoji("EG") },
  { code: "EE", name: "Estonia", flag: getFlagEmoji("EE") },
  { code: "FI", name: "Finland", flag: getFlagEmoji("FI") },
  { code: "FR", name: "France", flag: getFlagEmoji("FR") },
  { code: "GE", name: "Georgia", flag: getFlagEmoji("GE") },
  { code: "DE", name: "Germany", flag: getFlagEmoji("DE") },
  { code: "GR", name: "Greece", flag: getFlagEmoji("GR") },
  { code: "HK", name: "Hong Kong", flag: getFlagEmoji("HK") },
  { code: "HU", name: "Hungary", flag: getFlagEmoji("HU") },
  { code: "IS", name: "Iceland", flag: getFlagEmoji("IS") },
  { code: "IN", name: "India", flag: getFlagEmoji("IN") },
  { code: "ID", name: "Indonesia", flag: getFlagEmoji("ID") },
  { code: "IR", name: "Iran", flag: getFlagEmoji("IR") },
  { code: "IQ", name: "Iraq", flag: getFlagEmoji("IQ") },
  { code: "IE", name: "Ireland", flag: getFlagEmoji("IE") },
  { code: "IL", name: "Israel", flag: getFlagEmoji("IL") },
  { code: "IT", name: "Italy", flag: getFlagEmoji("IT") },
  { code: "JP", name: "Japan", flag: getFlagEmoji("JP") },
  { code: "JO", name: "Jordan", flag: getFlagEmoji("JO") },
  { code: "KZ", name: "Kazakhstan", flag: getFlagEmoji("KZ") },
  { code: "KE", name: "Kenya", flag: getFlagEmoji("KE") },
  { code: "KR", name: "Korea, South", flag: getFlagEmoji("KR") },
  { code: "KW", name: "Kuwait", flag: getFlagEmoji("KW") },
  { code: "LV", name: "Latvia", flag: getFlagEmoji("LV") },
  { code: "LB", name: "Lebanon", flag: getFlagEmoji("LB") },
  { code: "LT", name: "Lithuania", flag: getFlagEmoji("LT") },
  { code: "LU", name: "Luxembourg", flag: getFlagEmoji("LU") },
  { code: "MY", name: "Malaysia", flag: getFlagEmoji("MY") },
  { code: "MX", name: "Mexico", flag: getFlagEmoji("MX") },
  { code: "MA", name: "Morocco", flag: getFlagEmoji("MA") },
  { code: "NL", name: "Netherlands", flag: getFlagEmoji("NL") },
  { code: "NZ", name: "New Zealand", flag: getFlagEmoji("NZ") },
  { code: "NG", name: "Nigeria", flag: getFlagEmoji("NG") },
  { code: "NO", name: "Norway", flag: getFlagEmoji("NO") },
  { code: "PK", name: "Pakistan", flag: getFlagEmoji("PK") },
  { code: "PE", name: "Peru", flag: getFlagEmoji("PE") },
  { code: "PH", name: "Philippines", flag: getFlagEmoji("PH") },
  { code: "PL", name: "Poland", flag: getFlagEmoji("PL") },
  { code: "PT", name: "Portugal", flag: getFlagEmoji("PT") },
  { code: "QA", name: "Qatar", flag: getFlagEmoji("QA") },
  { code: "RO", name: "Romania", flag: getFlagEmoji("RO") },
  { code: "RU", name: "Russia", flag: getFlagEmoji("RU") },
  { code: "SA", name: "Saudi Arabia", flag: getFlagEmoji("SA") },
  { code: "RS", name: "Serbia", flag: getFlagEmoji("RS") },
  { code: "SG", name: "Singapore", flag: getFlagEmoji("SG") },
  { code: "SK", name: "Slovakia", flag: getFlagEmoji("SK") },
  { code: "SI", name: "Slovenia", flag: getFlagEmoji("SI") },
  { code: "ZA", name: "South Africa", flag: getFlagEmoji("ZA") },
  { code: "ES", name: "Spain", flag: getFlagEmoji("ES") },
  { code: "SE", name: "Sweden", flag: getFlagEmoji("SE") },
  { code: "CH", name: "Switzerland", flag: getFlagEmoji("CH") },
  { code: "SY", name: "Syria", flag: getFlagEmoji("SY") },
  { code: "TW", name: "Taiwan", flag: getFlagEmoji("TW") },
  { code: "TH", name: "Thailand", flag: getFlagEmoji("TH") },
  { code: "TR", name: "Turkey", flag: getFlagEmoji("TR") },
  { code: "UA", name: "Ukraine", flag: getFlagEmoji("UA") },
  { code: "AE", name: "United Arab Emirates", flag: getFlagEmoji("AE") },
  { code: "GB", name: "United Kingdom", flag: getFlagEmoji("GB") },
  { code: "US", name: "United States", flag: getFlagEmoji("US") },
  { code: "VN", name: "Vietnam", flag: getFlagEmoji("VN") },
];
